# Generated by Django 3.0.8 on 2020-07-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200724_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuários'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico')], max_length=12, verbose_name='Ícone'),
        ),
    ]
