# Generated by Django 3.0.8 on 2020-07-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200726_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criaçao')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizaçao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('feature', models.CharField(max_length=100, verbose_name='Feature')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descriçao')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Computador'), ('lni-leaf', 'Folha'), ('lni-layers', 'Dados')], max_length=20, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-rocket', 'Foguete'), ('lni-users', 'Usuários'), ('lni-mobile', 'Mobile')], max_length=12, verbose_name='Ícone'),
        ),
    ]
